name: Build GitHub pages

on:
  push:
    branches:
      - develop

jobs:

  build_html:
    runs-on: ubuntu-latest

    env:
      COMMIT_AUTHOR: Pages Deployment
      COMMIT_AUTHOR_EMAIL: action@github.com

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install docutils

    - name: Run rst2html
      run: make html

    - name: Commit to gh-pages
      run: |
        git branch -D gh-pages || true
        git checkout -b gh-pages
        git config user.name "${COMMIT_AUTHOR}"
        git config user.name "${COMMIT_AUTHOR_EMAIL}"
        git add optimade.html
        git commit -m "Deploy to GitHub Pages: ${SHA}"
        if git diff --cached --quiet; then
            exit 0
        fi

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        branch: gh-pages
        force: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
