name: Pre-commit checks

on: [push, pull_request]

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install pre-commit==2.2.0
    - name: Run pre-commit tests
      run: |
        pre-commit run --all-files
